services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - ~/Projects/plinko/postgres:/var/lib/postgresql/data
    restart: always
    environment: 
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: plinko
